/**
 * Korean. Keys are the English sentences themselves — see i18n.ts for why.
 *
 * Chess vocabulary follows what Korean players actually say rather than a
 * literal gloss: 캐슬링, 앙파상, 폰/나이트/비숍/룩/퀸/킹 are all loanwords in
 * ordinary use, while 수 (a move), 변화수 (a variation) and 정답 (the
 * solution) are native. Translating those into coined Korean would be
 * correct and unreadable.
 *
 * Anything missing here renders as its English original, so this file can
 * grow without any component knowing.
 */
export const ko: Record<string, string> = {
  // --- shell, navigation ---------------------------------------------------
  'Chess Vault': 'Chess Vault',
  'Your chess, in plain files.': '당신의 체스를, 평범한 파일로.',
  Home: '홈',
  Games: '게임',
  Studies: '스터디',
  Notes: '노트',
  Puzzles: '퍼즐',
  Tools: '도구',
  Settings: '설정',
  More: '더보기',
  Board: '보드',
  Editor: '편집기',
  Explorer: '탐색기',
  Repertoire: '레퍼토리',
  Dashboard: '대시보드',
  Books: '책',
  Themes: '테마',
  "This page isn't available.": '이 페이지는 사용할 수 없습니다.',
  Loading: '불러오는 중',

  // --- common actions ------------------------------------------------------
  Back: '뒤로',
  Forward: '앞으로',
  Start: '처음',
  Latest: '최신',
  Cancel: '취소',
  Save: '저장',
  Load: '불러오기',
  Create: '만들기',
  Add: '추가',
  Remove: '제거',
  Reset: '초기화',
  Close: '닫기',
  Retry: '다시 시도',
  Done: '완료',
  Paste: '붙여넣기',
  Import: '가져오기',
  Build: '만들기',
  List: '목록',
  Analyse: '분석',
  Skip: '건너뛰기',
  Hint: '힌트',
  Solution: '정답',
  Any: '전체',
  On: '켜짐',
  Puzzle: '퍼즐',
  Game: '게임',
  Moves: '수순',
  'Flip board': '보드 뒤집기',
  'Flip board (f)': '보드 뒤집기 (f)',
  'Start (↑)': '처음 (↑)',
  'Back (←)': '뒤로 (←)',
  'Forward (→)': '앞으로 (→)',
  'End (↓)': '끝 (↓)',
  'Choose promotion piece': '승격할 기물 선택',
  'Scroll left': '왼쪽으로 스크롤',
  'Scroll right': '오른쪽으로 스크롤',
  'Drag to resize · double-click to reset': '드래그해 크기 조절 · 더블클릭하면 원래대로',
  'Move to': '옮길 위치',
  'New collection…': '새 모음…',
  'Move into this new collection': '이 새 모음으로 옮기기',
  'Move to a collection': '모음으로 옮기기',
  Collection: '모음',
  'Empty collection.': '빈 모음입니다.',

  // --- analysis, board, editor --------------------------------------------
  'Delete this move and everything after it': '이 수와 그 이후를 모두 삭제',
  'Clear the board': '보드 비우기',
  'Has a comment': '주석 있음',
  'Play a move on the board, or load a FEN or PGN.':
    '보드에서 수를 두거나, FEN 또는 PGN을 불러오세요.',
  'Make mainline': '주 변화로 지정',
  'Load a position — FEN, PGN, or image': '국면 불러오기 — FEN, PGN 또는 이미지',
  'Load position': '국면 불러오기',
  'Paste from clipboard': '클립보드에서 붙여넣기',
  'Paste a FEN or PGN, then press Enter': 'FEN 또는 PGN을 붙여넣고 Enter를 누르세요',
  'click to choose, drop a file, or paste an image':
    '클릭해 선택하거나, 파일을 끌어놓거나, 이미지를 붙여넣으세요',
  Position: '국면',
  'Side to move': '둘 차례',
  'Castling rights': '캐슬링 권리',
  'En passant target': '앙파상 대상',
  'Halfmove clock': '하프무브 카운터',
  'Move number': '수 번호',
  'Legal position': '합법적인 국면',
  'Move: drag pieces around the board': '이동: 기물을 끌어 옮깁니다',
  'Erase: click a square to remove its piece': '지우기: 칸을 클릭하면 그 기물이 사라집니다',
  'Reset to the starting position': '시작 국면으로 되돌리기',
  'Position details (side to move, castling, FEN)': '국면 세부 정보 (둘 차례, 캐슬링, FEN)',
  Move: '이동',
  Erase: '지우기',

  // --- engine, review ------------------------------------------------------
  'Engine settings': '엔진 설정',
  'Engine on/off': '엔진 켜기/끄기',
  Threads: '스레드',
  Lines: '변화 수',
  Depth: '깊이',
  Hash: '해시',
  'Thinking…': '생각하는 중…',
  'Engine review — judge every move (?!/?/??) and measure accuracy':
    '엔진 리뷰 — 모든 수를 평가하고 (?!/?/??) 정확도를 측정합니다',
  Dismiss: '닫기',
  'Dismiss review': '리뷰 닫기',
  'Evaluation graph — click to jump to a move': '평가 그래프 — 클릭하면 그 수로 이동합니다',
  Reviewing: '리뷰 중',

  // --- explorer ------------------------------------------------------------
  'Opening book': '오프닝 북',
  'Manage books': '북 관리',
  'Explorer on/off': '탐색기 켜기/끄기',
  'Open this game': '이 게임 열기',
  'Top games': '주요 게임',
  'Build a book': '북 만들기',
  'No opening books yet. Drop PGN files into': '아직 오프닝 북이 없습니다. PGN 파일을 넣어 주세요:',

  // --- games ---------------------------------------------------------------
  'Back to games': '게임 목록으로',
  'Search players, openings, or ECO (e.g. Najdorf, B90)…':
    '선수, 오프닝 또는 ECO 검색 (예: Najdorf, B90)…',
  'Open on the analysis board': '분석 보드에서 열기',
  'Preview the final position': '최종 국면 미리 보기',
  'Search collection…': '모음 검색…',
  'Browse the indexed reference games': '색인된 참고 게임 둘러보기',
  'Game actions': '게임 동작',
  'Browse this player': '이 선수 둘러보기',
  'Archive month': '보관된 달',
  Annotated: '주석 있음',
  'View on chess.com (needs internet)': 'chess.com에서 보기 (인터넷 필요)',
  'Import a game': '게임 가져오기',
  'White (optional)': '백 (선택)',
  'Black (optional)': '흑 (선택)',
  'Date, e.g. 2026-08-08': '날짜, 예: 2026-08-08',
  'White rating': '백 레이팅',
  'Black rating': '흑 레이팅',
  'Event / tournament (optional)': '대회 (선택)',
  Result: '결과',
  'No reference games yet': '아직 참고 게임이 없습니다',
  'Elite games': '엘리트 게임',
  'offline — cached months only': '오프라인 — 저장된 달만',
  'Add to collection': '모음에 추가',

  // --- notes ---------------------------------------------------------------
  'Search notes…': '노트 검색…',
  'Rename this note': '이 노트 이름 바꾸기',
  'All notes': '모든 노트',
  Saved: '저장됨',
  'Saving…': '저장 중…',
  'Retry save': '저장 다시 시도',
  Unsaved: '저장 안 됨',
  Formatting: '서식',
  'Load a FEN or PGN into this board': '이 보드에 FEN 또는 PGN 불러오기',
  'Remove this board': '이 보드 제거',
  'Paste a FEN or PGN…': 'FEN 또는 PGN 붙여넣기…',
  'Play moves on the board, or paste a FEN/PGN.': '보드에서 수를 두거나, FEN/PGN을 붙여넣으세요.',

  // --- studies -------------------------------------------------------------
  'Search studies…': '스터디 검색…',
  'Paste a PGN here — a Lichess study export imports with all its chapters, comments and arrows.':
    '여기에 PGN을 붙여넣으세요 — Lichess 스터디 내보내기는 모든 챕터, 주석, 화살표와 함께 들어옵니다.',
  'Lichess username': 'Lichess 사용자명',
  'Double-click to rename': '더블클릭하면 이름을 바꿉니다',
  'Rename this collection': '이 모음 이름 바꾸기',
  'Rename this study': '이 스터디 이름 바꾸기',
  'Choose file': '파일 선택',
  'Import from Lichess': 'Lichess에서 가져오기',
  'No studies found.': '스터디가 없습니다.',
  'Unsaved changes — click to save now': '저장하지 않은 변경 — 클릭하면 바로 저장합니다',
  'Add a chapter': '챕터 추가',
  'Rename this chapter': '이 챕터 이름 바꾸기',
  'Add a sub-chapter': '하위 챕터 추가',

  // --- puzzles -------------------------------------------------------------
  'End of line': '변화 끝',
  'Back to the dashboard': '대시보드로',
  'Back to the puzzle': '퍼즐로',
  'Back to the book': '책으로',
  'Back to the position': '국면으로',
  'Back to the diagram': '다이어그램으로',
  'All books': '모든 책',
  'All themes': '모든 테마',
  'All puzzles in this book': '이 책의 모든 퍼즐',
  'Puzzle books': '퍼즐 책',
  'Puzzle dashboard': '퍼즐 대시보드',
  'Puzzle themes': '퍼즐 테마',
  'New book': '새 책',
  'Import PDF': 'PDF 가져오기',
  'Import a book PDF': '책 PDF 가져오기',
  'Add puzzle': '퍼즐 추가',
  'Add a puzzle': '퍼즐 추가',
  'Read diagrams': '다이어그램 읽기',
  'Re-run recognition on every draft with the learned font':
    '학습한 글꼴로 모든 초안을 다시 인식',
  'Peek at the book scan': '책 스캔 살짝 보기',
  'Zoom out': '축소',
  'Zoom in': '확대',
  'Show the whole page': '페이지 전체 보기',
  'Undo the last move': '마지막 수 되돌리기',
  'Ask Stockfish whether every solver move really wins':
    '풀이의 모든 수가 정말 이기는지 Stockfish에 확인',
  'Correct this puzzle against the book scan': '책 스캔과 대조해 이 퍼즐 바로잡기',
  'Previous puzzle': '이전 퍼즐',
  'Next puzzle': '다음 퍼즐',
  'Next unsolved': '다음 미해결',
  'Start over': '처음부터',
  'Grade the mainline — this is the only judged moment':
    '주 변화를 채점합니다 — 평가되는 순간은 여기뿐입니다',
  'Counts as a failed attempt': '실패한 시도로 기록됩니다',
  'Nothing entered yet — find the first move on the board.':
    '아직 입력이 없습니다 — 보드에서 첫 수를 찾으세요.',
  'Puzzle not found.': '퍼즐을 찾을 수 없습니다.',
  'That book does not exist.': '그런 책이 없습니다.',
  'Nothing matches these filters.': '이 조건에 맞는 것이 없습니다.',
  'Play the solution — every move, both sides.': '정답을 두세요 — 양쪽 모두, 모든 수를.',
  'Record the solution — every move, both sides.': '정답을 기록하세요 — 양쪽 모두, 모든 수를.',
  Solved: '해결',
  Attempts: '시도',
  'Win rate': '정답률',
  Failed: '실패',
  solved: '해결',
  failed: '실패',
  'Distinct puzzles whose latest attempt failed — always the review pool':
    '마지막 시도가 실패한 퍼즐 — 복습 대상입니다',
  'Review failed puzzles': '실패한 퍼즐 복습',
  'By difficulty': '난이도별',
  'All puzzle books': '모든 퍼즐 책',
  'Preview the position': '국면 미리 보기',
  Shelf: '책장',
  'Import a book': '책 가져오기',
  Difficulty: '난이도',
  'First press marks the piece, second the move (not counted as a fail)':
    '한 번 누르면 기물을, 두 번 누르면 수를 알려줍니다 (실패로 세지 않음)',
  'First move': '첫 수',
  'No puzzle database yet': '아직 퍼즐 데이터베이스가 없습니다',
  'Download the Lichess dump and build it once:':
    'Lichess 덤프를 내려받아 한 번만 만들면 됩니다:',
  Theme: '테마',
  Played: '플레이 횟수',
  'Finding a puzzle…': '퍼즐을 찾는 중…',
  'Try harder on boards that fail': '실패한 보드에 더 공을 들이기',
  'clearing the book': '책을 비우는 중',
  "reading the book's solutions": '책의 정답을 읽는 중',
  'Position from an image': '이미지에서 국면 읽기',
  'Choose an image of the diagram': '다이어그램 이미지 선택',
  'a screenshot or scan works best': '스크린샷이나 스캔이 가장 잘 됩니다',
  'Paste image': '이미지 붙여넣기',
  'paste image': '이미지 붙여넣기',
  'different image': '다른 이미지',
  'Drop the image': '이미지를 놓으세요',
  'or press Ctrl+V — dropping a file here works too':
    'Ctrl+V를 눌러도 되고, 파일을 여기에 끌어놓아도 됩니다',
  'Drag the four handles onto the corners of the diagram.':
    '네 모서리 손잡이를 다이어그램의 모서리에 맞추세요.',
  'Read position': '국면 읽기',
  'Black at the bottom': '흑이 아래쪽',

  // --- repertoire ----------------------------------------------------------
  'Search any opening or ECO code…': '오프닝 또는 ECO 코드 검색…',
  'New game': '새 게임',
  'Opponent strength': '상대 실력',
  'Set up a new game': '새 게임 설정',
  'Make your first move on the board.': '보드에서 첫 수를 두세요.',
  Rating: '레이팅',
  Opening: '오프닝',
  'Analyse this line': '이 변화 분석',
  White: '백',
  Black: '흑',

  // --- settings ------------------------------------------------------------
  Profile: '프로필',
  'Display name': '표시 이름',
  'How the app greets you': '앱이 당신을 부르는 이름',
  'chess.com username': 'chess.com 사용자명',
  'your chess.com handle': 'chess.com 아이디',
  'your Lichess handle': 'Lichess 아이디',
  Version: '버전',
  'Free software under the GPL-3.0.': 'GPL-3.0 자유 소프트웨어입니다.',
  'Source code': '소스 코드',
  Licences: '라이선스',
  'Desktop app': '데스크톱 앱',
  Appearance: '모양',
  'App theme': '앱 테마',
  Colours: '색',
  'Board theme': '보드 테마',
  Castling: '캐슬링',
  'How to castle': '캐슬링 방법',
  Pieces: '기물',
  'Piece set': '기물 세트',
  'Move sounds': '수 소리',
  Sound: '소리',
  Volume: '음량',
  // Deliberately not a bare 'Move'/'Capture': `Move` is already taken at the
  // top of this file for relocating a file ('이동'), and this dictionary is
  // keyed by the English string, so one word cannot carry both senses.
  'Move sound': '수 소리',
  'Capture sound': '기물 잡기 소리',
  'Rotate through all': '번갈아 재생',
  Deep: '낮게',
  Standard: '기본',
  Bright: '밝게',
  Sharp: '날카롭게',
  Long: '길게',
  Short: '짧게',
  'Rotating plays a different take each time, so a long analysis does not sound like one sample repeating. The sounds are synthesised, not recorded.':
    '번갈아 재생하면 매번 다른 테이크가 나오므로, 긴 분석에서도 같은 샘플이 반복되는 느낌이 없습니다. 이 소리들은 녹음이 아니라 합성한 것입니다.',
  Security: '보안',
  'Current password': '현재 비밀번호',
  'New password': '새 비밀번호',
  'Repeat new password': '새 비밀번호 확인',
  'Lichess token': 'Lichess 토큰',
  'Danger zone': '위험 구역',
  Server: '서버',
  Vault: '보관함',
  'Point this window at a server, or host a folder on this machine.':
    '이 창을 서버에 연결하거나, 이 기기의 폴더를 사용하세요.',
  'Switch…': '전환…',
  'Usernames pre-fill the archive browser on the Games page.':
    '사용자명은 게임 페이지의 보관함 검색에 미리 채워집니다.',
  'Save profile': '프로필 저장',
  'Play a click on moves, captures and checks.': '수, 기물 잡기, 체크에 소리를 냅니다.',
  'Two-factor authentication': '2단계 인증',
  'Turning it off needs a current code from your authenticator app.':
    '끄려면 인증 앱의 현재 코드가 필요합니다.',
  'Turn off 2FA': '2단계 인증 끄기',
  'Set up 2FA': '2단계 인증 설정',
  'Manual entry key:': '수동 입력 키:',
  'no scopes': '권한 없음',
  'A token ending in': '끝자리가',
  'is configured.': '인 토큰이 설정되어 있습니다.',
  'Wipe all data': '모든 데이터 삭제',
  'Wipe the entire vault?': '보관함 전체를 삭제할까요?',
  'Confirm your app password': '앱 비밀번호를 확인하세요',
  Language: '언어',
  'App language': '앱 언어',

  // --- auth ----------------------------------------------------------------
  Password: '비밀번호',
  'Authenticator code': '인증 앱 코드',
  'Use a different password': '다른 비밀번호 사용',

  // --- appearance option labels -------------------------------------------
  'Walnut (adaptive)': '월넛 (자동)',
  'Tournament green': '토너먼트 그린',
  'Classic brown': '클래식 브라운',
  Ocean: '오션',
  Slate: '슬레이트',
  Paper: '페이퍼',
  Forest: '포레스트',
  Rose: '로즈',
  Midnight: '미드나이트',
  Mono: '모노',
  'Move the king two squares (g1)': '킹을 두 칸 옮기기 (g1)',
  'Move the king onto the rook (h1)': '킹을 룩 위로 옮기기 (h1)',
  'Follow system': '시스템 설정 따르기',
  Light: '밝게',
  Dark: '어둡게',
  Cburnett: 'Cburnett',
  Merida: 'Merida',
  Chessnut: 'Chessnut',
  Pirouetti: 'Pirouetti',

  // --- home cards and the More page ---------------------------------------
  App: '앱',
  'Free board with engine and explorer': '엔진과 탐색기가 있는 자유 보드',
  'Set up any position': '원하는 국면 만들기',
  'Openings and ideas, in chapters': '오프닝과 아이디어를, 챕터로',
  'Markdown with live boards': '살아 있는 보드가 있는 마크다운',
  'Your collection, annotated': '주석이 달린 나의 모음',
  'Train tactics offline': '오프라인으로 전술 훈련',
  'Analyse any position with the engine': '엔진으로 어떤 국면이든 분석',
  'Set up any position from scratch': '처음부터 국면 만들기',
  'Browse opening statistics move by move': '한 수씩 오프닝 통계 보기',
  'Practise an opening against real games': '실제 기보를 상대로 오프닝 연습',
  'Password, 2FA, themes, tokens': '비밀번호, 2단계 인증, 테마, 토큰',

  // --- opponent strength (repertoire) -------------------------------------
  'Beginner (under 1400)': '입문 (1400 미만)',
  'Club (1400–1800)': '클럽 (1400–1800)',
  'Strong (1800–2200)': '상급 (1800–2200)',
  'Master (2200+)': '마스터 (2200+)',
  'All ratings': '전체',
  'Start position': '시작 국면',

  // --- difficulty and the dashboard hub -----------------------------------
  Train: '훈련',
  Easy: '쉬움',
  Medium: '보통',
  Hard: '어려움',
  Expert: '전문가',
  'Any difficulty': '난이도 전체',
  'Difficulty {hint}': '난이도 {hint}',

  // --- longer prose --------------------------------------------------------
  'Private instance — every game, study and puzzle here lives in plain files on its owner’s server.':
    '개인 인스턴스 — 여기의 모든 게임, 스터디, 퍼즐은 소유자의 서버에 평범한 파일로 저장됩니다.',
  'No password is set — anyone who can reach this server sees everything. Setting one turns the lock screen on.':
    '비밀번호가 설정되어 있지 않습니다 — 이 서버에 접근할 수 있는 누구나 모든 것을 볼 수 있습니다. 설정하면 잠금 화면이 켜집니다.',
  'Scan with your authenticator app, then enter the code it shows. Nothing is saved until the code checks out.':
    '인증 앱으로 스캔한 뒤, 표시된 코드를 입력하세요. 코드가 확인되기 전에는 아무것도 저장되지 않습니다.',
  'This permanently deletes every game, study, note, puzzle and book, and their history. There is no undo.':
    '모든 게임, 스터디, 노트, 퍼즐, 책과 그 기록을 영구히 삭제합니다. 되돌릴 수 없습니다.',
  'Adds a 6-digit authenticator code (Google Authenticator, 1Password, Aegis…) to the lock screen.':
    '잠금 화면에 6자리 인증 코드(Google Authenticator, 1Password, Aegis…)를 추가합니다.',
  'Verify & enable': '확인하고 켜기',
  'Reviewing puzzles you failed before — not counted, and a clean solve retires the puzzle from this list.':
    '전에 틀린 퍼즐을 복습하는 중입니다 — 기록에 세지 않으며, 깔끔하게 풀면 이 목록에서 빠집니다.',
  "No moves yet. The first move you play is the puzzle's first move to find.":
    '아직 수가 없습니다. 처음 두는 수가 이 퍼즐에서 찾아야 할 첫 수가 됩니다.',
  'The diagram from the book — make the board match it, then record the solution.':
    '책의 다이어그램입니다 — 보드를 여기에 맞춘 다음, 정답을 기록하세요.',
  'The book’s own scan — make the board match it.': '책의 스캔 원본입니다 — 보드를 여기에 맞추세요.',
  'Empty book. “Add puzzle” sets up the position on a board and records the full solution — both sides’ moves.':
    '빈 책입니다. “퍼즐 추가”로 보드에 국면을 만들고 양쪽의 수를 모두 포함한 정답을 기록하세요.',
  'Tip: click an opponent move to mark it “any move” (the book’s ~).':
    '팁: 상대의 수를 클릭하면 “아무 수나”로 표시됩니다 (책의 ~ 표기).',
  'No studies yet. A study is a set of annotated chapters — lines, comments, arrows — saved as plain PGN in':
    '아직 스터디가 없습니다. 스터디는 주석이 달린 챕터 묶음 — 변화수, 주석, 화살표 — 이며 평범한 PGN으로 저장됩니다:',
  "Training attempts only — review sessions don't count here, which is why this can differ from the review pool":
    '훈련 시도만 셉니다 — 복습은 여기에 포함되지 않으므로 복습 대상 수와 다를 수 있습니다',
  "Browse this player's online archive": '이 선수의 온라인 기보 보기',
  'Choose the book’s PDF': '책의 PDF 선택',
  'From this game ↗': '이 게임에서 ↗',
  'Set an app password first.': '먼저 앱 비밀번호를 설정하세요.',
  Offline: '오프라인',
  'This machine': '이 기기',
  'Set an app password': '앱 비밀번호 설정',
  'Change app password': '앱 비밀번호 변경',
  Copy: '복사',
  Browse: '둘러보기',
  All: '전체',

  // --- counts, times and the sentences that wrap a path -------------------
  'just now': '방금',
  '{n} min ago': '{n}분 전',
  '{n} h ago': '{n}시간 전',
  yesterday: '어제',
  '{n} days ago': '{n}일 전',
  'edited {when}': '{when} 수정',
  '{n} chapters': '챕터 {n}개',
  'not parseable': '읽을 수 없음',
  'that PGN parses into zero chapters': '이 PGN에서 챕터를 하나도 읽지 못했습니다',
  'No notes yet. A note is plain markdown in': '아직 노트가 없습니다. 노트는',
  'with interactive chess boards embedded anywhere in the text.':
    '에 저장되는 평범한 마크다운이며, 본문 어디에나 체스 보드를 넣을 수 있습니다.',
  "No PGN files found. Put game collections (e.g. Lichess Elite months, Lumbra's Gigabase exports) into":
    'PGN 파일이 없습니다. 기보 모음(예: Lichess Elite 월별 파일, Lumbra Gigabase 내보내기)을',
  'then come back here.': '에 넣은 뒤 다시 오세요.',
  'Drop PGN collections (Lichess Elite months, TWIC, Lumbra exports) into vault/sources and index them once:':
    'PGN 모음(Lichess Elite 월별 파일, TWIC, Lumbra 내보내기)을 vault/sources에 넣고 한 번만 색인하세요:',
  'Vault:': '보관함:',
  '— every game, study and puzzle lives there as plain files. Display settings live on this device.':
    '— 모든 게임, 스터디, 퍼즐이 평범한 파일로 그곳에 저장됩니다. 화면 설정은 이 기기에만 저장됩니다.',
  'solutions page': '정답 페이지',
  'book page': '책 페이지',
  'book diagram in its page': '페이지 안의 책 다이어그램',
  'book diagram': '책 다이어그램',
  'book name': '북 이름',
  Training: '훈련',
  'TOTP enrolment QR code': 'TOTP 등록 QR 코드',
  'Book title, e.g. “1001 Winning Chess Sacrifices”': '책 제목, 예: “1001 Winning Chess Sacrifices”',
  // --- status, feedback and confirmations ---------------------------------
  Copied: '복사됨',
  'Could not load that.': '불러올 수 없습니다.',
  'Could not add this game': '이 게임을 추가할 수 없습니다',
  'Add this game to the collection': '이 게임을 모음에 추가',
  'In the collection': '모음에 있음',
  'Starting position': '시작 국면',
  Engine: '엔진',
  'Turn the engine off': '엔진 끄기',
  'Turn the engine on': '엔진 켜기',
  'Hide the evaluation graph': '평가 그래프 숨기기',
  'Show the evaluation graph': '평가 그래프 보기',
  'Analyse this position': '이 국면 분석',
  'That PGN could not be read.': 'PGN을 읽을 수 없습니다.',
  'That FEN could not be read.': 'FEN을 읽을 수 없습니다.',
  'vault server unreachable': '보관함 서버에 연결할 수 없습니다',
  'Searching…': '검색 중…',
  'Checking…': '확인 중…',
  Continue: '계속',
  Unlock: '잠금 해제',
  'Wrong password.': '비밀번호가 틀렸습니다.',
  'Wrong authenticator code.': '인증 코드가 틀렸습니다.',
  'Too many attempts — wait a few minutes.': '시도가 너무 많습니다 — 몇 분 뒤에 다시 하세요.',

  // --- editor --------------------------------------------------------------
  'White O-O': '백 O-O',
  'White O-O-O': '백 O-O-O',
  'Black O-O': '흑 O-O',
  'Black O-O-O': '흑 O-O-O',

  // --- explorer ------------------------------------------------------------
  'Local books': '로컬 북',
  'Online (via proxy)': '온라인 (프록시 경유)',
  'Hide the explorer': '탐색기 숨기기',
  'Show the explorer': '탐색기 보기',
  'Out of book': '정석을 벗어남',
  'Show fewer moves': '수 적게 보기',
  'Original sources unknown': '원본 출처를 알 수 없음',
  'Delete this book (the source PGNs stay)': '이 북 삭제 (원본 PGN은 남습니다)',
  'Delete this opening book?': '이 오프닝 북을 삭제할까요?',
  Delete: '삭제',

  // --- games ---------------------------------------------------------------
  Added: '추가됨',
  'Show all games': '모든 게임 보기',
  'Show bookmarked games only': '즐겨찾기한 게임만 보기',
  'Remove bookmark': '즐겨찾기 해제',
  Bookmark: '즐겨찾기',
  Rename: '이름 바꾸기',
  'View online': '온라인에서 보기',
  'Remove this game from the collection?': '이 게임을 모음에서 뺄까요?',
  'could not load that game': '그 게임을 불러오지 못했습니다',
  'could not add that game': '그 게임을 추가하지 못했습니다',
  'could not import that game': '그 게임을 가져오지 못했습니다',
  'rename failed': '이름을 바꾸지 못했습니다',
  'could not rename': '이름을 바꾸지 못했습니다',
  'save failed': '저장하지 못했습니다',
  '· needs internet': '· 인터넷 필요',
  Event: '대회',
  Date: '날짜',
  Auto: '자동',
  'Result from the pasted moves': '붙여넣은 수에서 결과 판단',
  'White won': '백 승',
  'Black won': '흑 승',
  Draw: '무승부',

  // --- notes ---------------------------------------------------------------
  'New note': '새 노트',
  'New collection': '새 모음',
  'Note name': '노트 이름',
  'Collection name': '모음 이름',
  'Delete this note': '이 노트 삭제',
  'Back to reading': '읽기로 돌아가기',
  'Edit this note': '이 노트 편집',
  Edit: '편집',
  Bold: '굵게',
  Italic: '기울임',
  Strikethrough: '취소선',
  Code: '코드',
  Heading: '제목',
  Subheading: '소제목',
  'Bulleted list': '글머리 목록',
  'Numbered list': '번호 목록',
  Quote: '인용',
  'Insert a board': '보드 넣기',

  // --- puzzles: trainer feedback ------------------------------------------
  'Play a move on the board.': '보드에서 수를 두세요.',
  'Solved!': '정답입니다!',
  'Solved with help.': '힌트를 보고 맞혔습니다.',
  'Not this time.': '이번엔 아닙니다.',
  'Checking your answer…': '답을 확인하는 중…',
  'That is not it — it rolls back, try again.': '아닙니다 — 되돌립니다, 다시 해 보세요.',
  'Opponent is moving…': '상대가 두는 중…',
  'Keep looking — find the best move.': '계속 찾아보세요 — 최선의 수를 찾는 겁니다.',
  'Back to dashboard': '대시보드로',
  Review: '복습',
  'That is the book line. Retry it clean later.':
    '책의 변화가 맞습니다. 나중에 힌트 없이 다시 해 보세요.',
  'Off the book at the end — but the engine approves. Solved.':
    '끝에서 책과 갈라졌지만 엔진이 인정합니다. 정답입니다.',
  'Exactly as the book has it.': '책과 정확히 같습니다.',
  'Not quite — the marked move is where it goes wrong.':
    '아쉽습니다 — 표시된 수에서 어긋납니다.',
  'Correct so far, but the book line goes further.':
    '여기까진 맞지만, 책의 변화는 더 이어집니다.',
  'Explore freely — only the mainline is judged on submit.':
    '자유롭게 살펴보세요 — 제출할 때 채점되는 것은 주 변화뿐입니다.',
  'Engine agrees': '엔진도 동의',
  'Engine agrees: every solver move keeps a decisive advantage.':
    '엔진도 동의합니다: 풀이의 모든 수가 결정적인 우위를 유지합니다.',
  'any move': '아무 수나',
  'Any move accepted here (click to require this exact move)':
    '여기서는 아무 수나 받습니다 (클릭하면 이 수만 인정합니다)',
  'That puzzle does not exist.': '그런 퍼즐이 없습니다.',

  // --- puzzles: books, tiers and imports ----------------------------------
  Diagram: '다이어그램',
  Solutions: '정답',
  'not attempted': '시도 안 함',
  Draft: '초안',
  'Book solution': '책의 정답',
  "The book's exact solution — parsed and verified, or entered by hand":
    '책에 있는 그대로의 정답 — 해석해 검증했거나 직접 입력한 것',
  'Engine + book': '엔진 + 책',
  'Engine solution, corroborated by the book text': '책의 글이 뒷받침하는 엔진 정답',
  'Engine solution': '엔진 정답',
  'Engine solution (decisive line, no text corroboration)':
    '엔진 정답 (결정적인 변화, 글의 뒷받침은 없음)',
  'Engine guess': '엔진 추측',
  'Engine best line only — nothing decisive found; check the source if it feels off':
    '엔진의 최선 변화뿐 — 결정적인 것을 찾지 못했습니다. 이상하면 원본을 확인하세요',
  'Imported diagram awaiting a solution — open it to enter one':
    '정답을 기다리는 가져온 다이어그램 — 열어서 입력하세요',
  'Record solution': '정답 기록',
  Fix: '고치기',
  'could not create the book': '책을 만들지 못했습니다',
  'Delete this book and its progress': '이 책과 진행 상황 삭제',
  'Delete this book and its progress?': '이 책과 진행 상황을 삭제할까요?',
  'Reset all progress in this book': '이 책의 진행 상황 초기화',
  'Reset all progress in this book?': '이 책의 진행 상황을 초기화할까요?',
  'Close — the scan keeps running': '닫기 — 스캔은 계속 돌아갑니다',
  'Update in place': '제자리에서 갱신',
  'Re-reads the book and replaces each puzzle with what it finds. Anything the import misses this time is left as it is.':
    '책을 다시 읽어 각 퍼즐을 찾은 것으로 바꿉니다. 이번 가져오기가 놓친 것은 그대로 둡니다.',
  'Clear and rebuild': '비우고 다시 만들기',
  'Empties the book first, so it holds exactly what this import produces. Your attempt history is kept either way.':
    '책을 먼저 비워서 이번 가져오기의 결과만 담기게 합니다. 어느 쪽이든 시도 기록은 유지됩니다.',
  'Each one replays the move the book prints, from the position on the page.':
    '하나하나가 페이지의 국면에서 책이 인쇄한 수를 재생한 것입니다.',
  'Too few solutions replayed for this to be trusted — treat these as a starting point and check them.':
    '재생된 정답이 너무 적어 신뢰하기 어렵습니다 — 출발점으로 삼고 직접 확인하세요.',
  'Positions are unread for now: confirming the first draft teaches this book’s font.':
    '아직 국면을 읽지 못했습니다. 첫 초안을 확인해 주면 이 책의 글꼴을 배웁니다.',
  '— still scanning': '— 아직 스캔 중',
  Hide: '숨기기',
  'No attempts yet — go solve something.': '아직 시도가 없습니다 — 뭐라도 풀어 보세요.',
  'Nothing matches this filter.': '이 조건에 맞는 것이 없습니다.',
  'Wipe attempts, history and the review pool': '시도, 기록, 복습 대상을 모두 지우기',
  'Wipe all attempts, history and the review pool?':
    '시도, 기록, 복습 대상을 모두 지울까요?',
  'Wipe everything': '전부 지우기',

  // --- position from an image ----------------------------------------------
  'No image in the clipboard — copy or snip one first.':
    '클립보드에 이미지가 없습니다 — 먼저 복사하거나 잘라 두세요.',
  'That drop had no image file.': '놓은 것에 이미지 파일이 없습니다.',
  'Set up by hand': '직접 만들기',
  'Load into the editor': '편집기로 불러오기',

  // --- puzzle theme groups -------------------------------------------------
  'Game phase': '게임 단계',
  Checkmates: '메이트',
  'Tactical motifs': '전술 모티프',
  Attacks: '공격',
  'Special moves': '특수한 수',
  Goals: '목표',
  Length: '길이',
  Source: '출처',

  // --- the demo ------------------------------------------------------------
  'Demo — everyone shares this vault and it resets regularly. Do not put anything private here.':
    '데모 — 이 보관함은 모두가 함께 쓰며 주기적으로 초기화됩니다. 개인적인 내용은 넣지 마세요.',
  // --- demo ----------------------------------------------------------------
  'This is a demo': '이것은 데모입니다',
  'Everything you change here lives in this browser tab and disappears when you reload. Your profile, password, two-factor authentication, the Lichess token and the vault itself need a server of your own — install the app or host it, and this page becomes the real thing.':
    '여기서 바꾼 것은 모두 이 브라우저 탭에만 남고 새로고침하면 사라집니다. 프로필, 비밀번호, 2단계 인증, Lichess 토큰, 그리고 보관함 자체는 당신의 서버가 있어야 합니다 — 앱을 설치하거나 직접 호스팅하면 이 페이지가 진짜가 됩니다.',
  'No games from this position in “{book}”.': '“{book}”에는 이 국면의 기보가 없습니다.',
  'The demo book covers the first {plies} plies.': '데모 북은 처음 {plies}수까지만 담고 있습니다.',
  'Demo — this is a sample vault of your own. Edit anything; a reload puts it back.':
    '데모 — 당신만의 예시 보관함입니다. 무엇이든 고쳐 보세요. 새로고침하면 되돌아갑니다.',
};
