/**
 * Pack demo-seed/ into a TS module the static demo can import.
 *
 * The demo has no server and no disk, so its starting vault has to arrive
 * as part of the bundle. This keeps demo-seed/ as ordinary files anybody
 * can read and edit — the generated module is derived, never edited.
 *
 *   npx tsx scripts/build-demo-seed.ts
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve, sep } from 'node:path';
import { REPO_ROOT } from '../server/paths.ts';

const SEED_DIR = resolve(REPO_ROOT, 'demo-seed');
const OUT = resolve(REPO_ROOT, 'web/src/demo/seed.ts');

const files: Record<string, string> = {};
for (const entry of readdirSync(SEED_DIR, { recursive: true, encoding: 'utf-8' })) {
  const full = resolve(SEED_DIR, entry);
  if (!statSync(full).isFile()) continue;
  files[entry.split(sep).join('/')] = readFileSync(full, 'utf-8');
}

const names = Object.keys(files).sort();
const bytes = names.reduce((sum, name) => sum + Buffer.byteLength(files[name]!), 0);

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-demo-seed.ts — do not edit.\n` +
    `// ${names.length} files, ${Math.round(bytes / 1024)} KB, from demo-seed/.\n` +
    `export const SEED: Record<string, string> = ${JSON.stringify(
      Object.fromEntries(names.map((name) => [name, files[name]])),
      null,
      2,
    )};\n`,
);

console.log(`demo seed: ${names.length} files, ${Math.round(bytes / 1024)} KB -> ${OUT}`);
