/**
 * Collect the licence notices of the Rust crates the native core is built
 * from, into `licenses/rust-crates.txt`.
 *
 *   npx tsx scripts/collect-crate-licenses.ts
 *
 * Why this exists at all: the licence page and `dependencies.txt` are
 * generated by walking `node_modules` (web/vite.licenses.ts), and that walk
 * cannot see a cargo dependency. Since 0.5.0 the desktop installer carries
 * `chessvault-core`, so 48 crates are CONVEYED to whoever installs it —
 * mostly MIT and Apache-2.0, both of which want their notice in every copy.
 * A hand-kept list would be exactly the kind of thing that goes stale one
 * `cargo add` later, so this reads the lockfile instead, and
 * `npm run check:repo` fails if the output no longer matches it.
 *
 * The texts come from the crate sources cargo already downloaded, so this
 * needs a machine that has built the crate at least once (`cargo build` in
 * `native/`). It is not part of any build: the output is committed, because
 * the web and demo builds have no cargo and must still be able to ship the
 * notice.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';

const REPO = resolve(import.meta.dirname, '..');
const LOCK = resolve(REPO, 'native', 'Cargo.lock');
const OUT = resolve(REPO, 'licenses', 'rust-crates.txt');
/** Our own crate: its licence is the app's, and it is not third-party. */
const OWN = 'chessvault-core';

export interface Crate {
  name: string;
  version: string;
  license: string;
  text: string | null;
}

/** The `[[package]]` blocks of a Cargo.lock, which is all we need from it. */
export function lockCrates(lock: string): { name: string; version: string }[] {
  const out: { name: string; version: string }[] = [];
  for (const block of lock.split('[[package]]').slice(1)) {
    const name = /^\s*name\s*=\s*"(.+)"/m.exec(block)?.[1];
    const version = /^\s*version\s*=\s*"(.+)"/m.exec(block)?.[1];
    if (name && version && name !== OWN) out.push({ name, version });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

/** Where cargo unpacked a crate's source, whichever registry it came from. */
function crateDir(name: string, version: string): string | null {
  const roots = resolve(homedir(), '.cargo', 'registry', 'src');
  if (!existsSync(roots)) return null;
  for (const registry of readdirSync(roots)) {
    const dir = resolve(roots, registry, `${name}-${version}`);
    if (existsSync(dir)) return dir;
  }
  return null;
}

function read(dir: string): { license: string; text: string | null } {
  const manifest = readFileSync(resolve(dir, 'Cargo.toml'), 'utf-8');
  const license = /^\s*license\s*=\s*"(.+)"/m.exec(manifest)?.[1] ?? 'see crate';
  // Several crates ship LICENSE-MIT *and* LICENSE-APACHE for their dual
  // licence; both are the offer, so both travel.
  const files = readdirSync(dir).filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f)).sort();
  const text = files.length
    ? files
        .map((f) => `--- ${f} ---\n\n${readFileSync(resolve(dir, f), 'utf-8').trim()}`)
        .join('\n\n')
    : null;
  return { license, text };
}

export function notice(crates: Crate[]): string {
  const counts = new Map<string, number>();
  for (const c of crates) counts.set(c.license, (counts.get(c.license) ?? 0) + 1);

  const head = [
    'Rust crates (the native core, desktop app only)',
    '===============================================',
    '',
    'Generated from native/Cargo.lock by scripts/collect-crate-licenses.ts.',
    'These are the crates `chessvault-core` is built from — the optional',
    'native fast path the desktop installer carries since 0.5.0. A build',
    'without it (a source checkout, a server, the web app) contains none of',
    'them.',
    '',
    `${crates.length} crates.`,
    '',
    ...[...counts]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([license, n]) => `  ${String(n).padStart(4)}  ${license}`),
    '',
    // The manifest check:repo compares against the lockfile. Keeping it in
    // the file means the check needs no cargo and no network.
    'Crates covered:',
    ...crates.map((c) => `  ${c.name} ${c.version}`),
    '',
  ];

  const body = crates.map((c) => {
    const bar = '-'.repeat(76);
    return [
      bar,
      `${c.name} ${c.version}  (${c.license})`,
      bar,
      '',
      c.text ??
        `No licence file ships in this crate. It declares ${c.license}; the full ` +
          'text of that licence is alongside this file.',
      '',
    ].join('\n');
  });

  return [...head, ...body].join('\n');
}

if (import.meta.filename === process.argv[1]) {
  const wanted = lockCrates(readFileSync(LOCK, 'utf-8'));
  const missing: string[] = [];
  const crates: Crate[] = wanted.map(({ name, version }) => {
    const dir = crateDir(name, version);
    if (!dir) {
      missing.push(`${name} ${version}`);
      return { name, version, license: 'see crate', text: null };
    }
    return { name, version, ...read(dir) };
  });

  if (missing.length) {
    console.error(
      `collect-crate-licenses: ${missing.length} crate(s) are not in the local cargo registry:\n` +
        missing.map((m) => `  ${m}`).join('\n') +
        '\n\nRun `cargo build --release` in native/ first — the texts come from\n' +
        'the sources cargo downloads, and a notice with holes in it is worse\n' +
        'than none.',
    );
    process.exit(1);
  }

  writeFileSync(OUT, notice(crates));
  const withText = crates.filter((c) => c.text).length;
  console.log(
    `rust-crates.txt: ${crates.length} crates, ${withText} with their own licence text`,
  );
}
