/**
 * Vendors extra piece sets from lichess-org/lila into one committed CSS
 * file, embedded as data URIs (the same shape as chessground's bundled
 * cburnett). Only GPL-compatible sets are taken — licenses per lila's
 * COPYING.md:
 *   merida GPLv2+ · chessnut Apache-2.0 · pirouetti AGPLv3+
 *   fantasy, spatial, celtic MIT (Maurizio Monge)
 *   kiwen-suwi CC BY 4.0 (neverRare) · mpchess GPLv3+ (Maxime Chupin)
 *   rhosgfx CC0 1.0 (RhosGFX)
 * The many sadsnake1 sets, california, caliente, xkcd etc. are CC
 * BY-NC-SA — the NC clause fails this app's redistribution bar — and the
 * "freeware" sets (alpha, leipzig, chess7…) have no licence at all.
 * cburnett (GPLv2+) ships with chessground and stays the default.
 *
 *   node scripts/setup-pieces.mjs   # regenerates web/src/piece-sets.css
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SETS = [
  'merida',
  'chessnut',
  'pirouetti',
  'fantasy',
  'spatial',
  'celtic',
  'kiwen-suwi',
  'mpchess',
  'rhosgfx',
];
const ROLES = { P: 'pawn', N: 'knight', B: 'bishop', R: 'rook', Q: 'queen', K: 'king' };
const BASE = 'https://raw.githubusercontent.com/lichess-org/lila/master/public/piece';

// One file PER SET, not one file for all of them: each becomes its own
// lazy chunk, dynamically imported the first time that set is chosen
// (store/prefs.ts). Nine sets in one eagerly-imported stylesheet would
// put ~340 KB of art in the main CSS bundle for a choice most people
// never change off cburnett.
const dir = resolve(dirname(fileURLToPath(import.meta.url)), '../web/src/pieces');
mkdirSync(dir, { recursive: true });

for (const set of SETS) {
  const out = [
    '/* GENERATED by scripts/setup-pieces.mjs — do not edit by hand.',
    ' * Piece art vendored from lichess-org/lila (licenses in file header',
    " * of the generator). Selected via <html data-pieces='...'> and",
    ' * lazy-imported by store/prefs.ts. */',
  ];
  for (const color of ['w', 'b']) {
    for (const [letter, role] of Object.entries(ROLES)) {
      const url = `${BASE}/${set}/${color}${letter}.svg`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: ${res.status}`);
      const svg = await res.text();
      const b64 = Buffer.from(svg).toString('base64');
      const colorName = color === 'w' ? 'white' : 'black';
      out.push(
        `[data-pieces='${set}'] .cg-wrap piece.${role}.${colorName} { background-image: url('data:image/svg+xml;base64,${b64}'); }`,
      );
    }
  }
  writeFileSync(resolve(dir, `${set}.css`), `${out.join('\n')}\n`);
  console.log(`${set}: 12 pieces embedded`);
}
console.log(`wrote ${dir}/<set>.css`);
