/**
 * Vendors extra piece sets from lichess-org/lila into one committed CSS
 * file, embedded as data URIs (the same shape as chessground's bundled
 * cburnett). Only GPL-compatible sets are taken — licenses per lila's
 * COPYING.md: merida GPLv2+, chessnut Apache-2.0, pirouetti AGPLv3+.
 * cburnett (GPLv2+) ships with chessground and stays the default.
 *
 *   node scripts/setup-pieces.mjs   # regenerates web/src/piece-sets.css
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SETS = ['merida', 'chessnut', 'pirouetti'];
const ROLES = { P: 'pawn', N: 'knight', B: 'bishop', R: 'rook', Q: 'queen', K: 'king' };
const BASE = 'https://raw.githubusercontent.com/lichess-org/lila/master/public/piece';

const out = [
  '/* GENERATED by scripts/setup-pieces.mjs — do not edit by hand.',
  ' * Piece art vendored from lichess-org/lila (licenses in file header',
  ' * of the generator). Selected via <html data-pieces="...">. */',
];

for (const set of SETS) {
  for (const color of ['w', 'b']) {
    for (const [letter, role] of Object.entries(ROLES)) {
      const url = `${BASE}/${set}/${color}${letter}.svg`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: ${res.status}`);
      const svg = await res.text();
      const b64 = Buffer.from(svg).toString('base64');
      const colorName = color === 'w' ? 'white' : 'black';
      out.push(
        `[data-pieces='${set}'] .cg-wrap piece.${role}.${colorName} { background-image: url('data:image/svg+xml;base64,${b64}'); }`,
      );
    }
  }
  console.log(`${set}: 12 pieces embedded`);
}

const dest = resolve(dirname(fileURLToPath(import.meta.url)), '../web/src/piece-sets.css');
writeFileSync(dest, `${out.join('\n')}\n`);
console.log(`wrote ${dest}`);
